service: java-app        # nombre del servicio, distinto si ya tienes PHP
runtime: java17
instance_class: F1
automatic_scaling:
  max_instances: 5
handlers:
  - url: /.*
    script: this field is required, but ignored